rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
			url(r'^$', views.index, name = 'index'),
			url(r'^login/$', views.user_login, name='login'),
			url(r'^logout/$', views.user_logout, name='logout'),
			url(r'^restricted/$', views.restricted, name='restricted'),
			url(r'about/', views.about, name = 'about'),
			url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name = 'show_category'),
			url(r'^add_category/$', views.add_category, name='add_category'),
			url( r'^(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
			url(r'^category/(?P<category_name_slug>[\w\-]+)/like/$', views.likeCategory, name = 'likeCategory'),
			url(r'^register/$', views.register, name='register'),		
			url(r'^new/$', views.new, name = 'new')
]			

tango_with_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/models.py
from django.db import models

from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique = True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Categories'
		
	def __str__(self): 
		return self.name

class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title

class UserProfile(models.Model):
	# This line is required. Links UserProfile to a User model instance
	user = models.OneToOneField(User)

	# The additional attributes as we wish to include.
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __str__(self):
		return self.user.username

		

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import UserProfile
from rango.models import Category, Page

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=128,
		help_text = "Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	# An inline class to provide additional information on the form.
	class Meta:
		# Provide an association between the ModelForm and a models
		model = Category
		fields = ('name', )

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=128, 
		help_text = "Please enter the title of the page.")
	url = forms.URLField(max_length=200,
		help_text = "Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	class Meta:
		# Provide an association between the ModelForm and a model
		model= Page
		# What fields do we want to include inour form?
		# This way we don't need every field in the model present
		# Some fields may allow NULL values, so we may not want to include them.
		# Here, we are hiding the foreign key,
		# we can either exclude the category field from the form,
		exclude = ('category', )
		# or specify the fields to include (i.e not include the ctaegory field)
		# fields = ('title', 'url', 'views') 
	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get('url')

		if url and not url.startswith('http://'):
			url = "http://" + url
			cleaned_data['url'] = url
			return cleaned_data

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields =('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

def new(request):
	context_dict = {}
	return render(request, 'rango/base_bootstrap.html', context=context_dict)

def index(request):
	#request.session.set_test_cookie()
	category_list = Category.objects.order_by('-likes')[:5]
	page_list = Page.objects.order_by('-views')[:5]
	context_dict = {'categories':category_list, 'pages': page_list }
	# Get the type of request , GET or POST
	#print(request.method)
	# Print out the name of the User logged in,if None, it'll return Anonymous User
	#print(request.user)

	# Obtain our Response object early so we can add cookie information	

	# Call function to handle the cookies
	return render(request, 'rango/index.html', context = context_dict)

def about(request):
	#if request.session.test_cookie_worked():
		#print("TEST COOKIE WORKED")
		#request.session.delete_test_cookie()
	context_dict = {'text1': 'Moses Benjamin', 
					'text2': 'I uploaded this image: '
				}
	visitor_cookie_handler(request) 
	context_dict['visits'] = request.session['visits']
	context_dict['last_visit'] = request.session['last_visit']
	response = render(request, 'rango/about.html', context = context_dict)
	return response


def show_category(request, category_name_slug):
	context_dict = {}

	try:
		# Can we find a category name slug with the given name?
		#If we can't, the .get() method raises a DoesNotExist exception
		# So the .get() method returns one model instance or raises an exception
		category = Category.objects.get(slug = category_name_slug)

		# Retrieve all of the associated pages
		# Note that filter() returns a list of page objects or an empty list
		pages = Page.objects.filter(category = category)

		# Adds our results list to the template context under name pages
		context_dict['pages'] = pages
		# We also add the category object from the 
		#database to the context dictionary
		# We'll use this in the template to verify that the category exist
		context_dict['category'] = category
	except Category.DoesNotExist:
		# We get here iF we didnt find the specified category
		# Don't do anything
		# the template eill display the "no category" message for us.
		context_dict['pages'] = None
		context_dict['category'] = None

	# Go render the response and return it to the client
	return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
	form = CategoryForm()

	# A HTTP POST?
	if request.method == 'POST':
		form = CategoryForm(request.POST)

		# Have we been provided with a valid form?
		if form.is_valid():
		# Save the new category to the database
			form.save(commit=True)
			# Now that the category is saved
			# We could give a confirmatory message
			# But since the most recent category added is on the index page_list
			# Then we can direct the user back to the index page
			return index(request)
			# The sipplied form contained errors
			# just print them to the terminal
		print(form.errors)

	# Will handle the bad form, new form, or no form supplied cases
	# Render the form with error messages(if any).
	return render(request, 'rango/add_category.html', {'form': form}) 

@login_required
def add_page(request, category_name_slug):
	try:
		category = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		category = None

	form = PageForm()
	if request.method == 'POST':
		form = PageForm(request.POST)
		if form.is_valid():
			if category:
				page = form.save(commit=False)
				page.category = category
				page.views = 0
				page.save()
			return show_category(request, category_name_slug)
		else:
			print(form.errors)

	return render(request, 'rango/add_page.html', {'form': form, 'category': category})


def likeCategory(request, category_name_slug):
	category = get_object_or_404(Category, slug=category_name_slug)
	try:
		selected_category = Category.objects.get(slug=request.POST['category'])
	except (KeyError, Category.DoesNotExist):
		return render(request, 'rango/category.html', 
			{'category': category, 'error_message': 'Check the checkbox !'})

	else:
		selected_category.likes += 1
		selected_category.save()
	#return HttpResponseRedirect(reverse('rango:index', args=('')))
	return show_category(request, category_name_slug)

def register(request):
	# A boolean value for telling the template
	# whether the registration was successful.
	# Set to False initially. Code changes value to
	# True when the registration succeeds.	
	registered = False

	# If it's a HTTP POST, we're interested in processing form data
	if request.method == 'POST':
		# Attempt to grab informaton from the raw form information
		# Note that we make use of both UserForm And UserProfileForm.
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		# If the two fields are valid...
		if user_form.is_valid() and profile_form.is_valid():
			# Save the User's form data to the database
			user = user_form.save()

			# Now we hash the password with the set_password method
			# Once hashed, we can update the user object
			user.set_password(user.password)
			user.save()

			# Now sort out the UserProfile instance
			#Since we need to set the user attribute ourselves,
			# set commit=False. This delays saving the model
			# until we're ready to avoid integrity problems.
			profile = profile_form.save(commit=False)
			profile.user = user

			# Did the user provide a profile picture ?
			# If so, we need to get it from the input form and
			# put it in the UserProfile model
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			# Now save the UserProfile model instance.
			profile.save()

			# Update our variable to indicate that thet the template
			# registration was successful.
			registered = True

		else:
				# Invalid form or forms - mistakes or something else?
				# Print problems to the terminal
				 print(user_form.errors, profile_form.errors)
	else:
		# Not a HTTP POST, so we render our form using two modelForm instances.
		# These forms will be blank, ready for user input.
		user_form = UserForm()
		profile_form = UserProfileForm()

	# Render the template depending on the context.
	return render(request,
		'rango/register.html',
		{'user_form': user_form,
		'profile_form': profile_form,
		'registered': registered,})
			 	
def user_login(request):
	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('rango:index'))
			else:
				return render(request, 'rango/login.html',{'error_message':
					'Your account has been disabled.'})
		else:

			return render(request, 'rango/login.html',
				{'error_message': 'Username and Password Mismatch !'})
	else:
		return render(request, 'rango/login.html',{})

@login_required
def restricted(request):
	return render(request,'rango/restricted.html',
		{'text': "Since you're logged in, you can see this text!"})

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_value=None):
	val = request.session.get(cookie)
	if not val:
		val = default_value
	return val

def visitor_cookie_handler(request):
	# Get the number of visits to the site
	# We use the COOKIES.get() function to obtain the visits cookie.
	# If the cookie exists, the value returned is casted to an integer.
	# If the cookie doesn't exist, then the default value of 1 is used.
	visits = int(get_server_side_cookie(request,'visits', '1'))
	last_visit_cookie = get_server_side_cookie(request,
		'last_visit', str(datetime.now())) 
	last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

	# If it's been more than a day since the last visit...
	if (datetime.now() - last_visit_time).seconds > 0:
		visits  =visits + 1
		#update the last visit cookie now that we have updated the count
		request.session['last_visit'] = str(datetime.now())

	else:
		visits =1
		# set the last visit cookie
		request.session['last_visit'] = last_visit_cookie

	# Update/set the visits cookie
	request.session['visits'] = visits	

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block%}
About
{% endblock %}
{% block body_block%}
	<img src="{% static 'images/Sunday Moses6.jpg'%}" class="mx-auto d-block rounded-circle img-fluid " alt='My picture' /><br/>
	<h5 class="text-center">{{ text1 }}</h5>
<!--	<p>{{ text2 }} </p>
<img src='{{ MEDIA_URL }}cat.jpg'>
	</br>-->
{% endblock %}
{% block footer%}
<p class="text-center">Current date and time: {{ last_visit }}.</p>
<h3><li><a href='{% url 'rango:about' %}'>Top</a></li></h3>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}
 Add category
{% endblock %}
{% block body_block%}
		<form id="category_form" method="post" action="/rango/add_category/">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
		{% for field in form.visible_fields %}
		<h3><strong>{{ field.errors }}</strong></h3>
		<h5>{{ field.help_text }}</h5>
		{{ field }}
		{% endfor %}
		<input type="submit" name="submit" value="Create Category" class="bg-light"/>
		</form><br/>
{% endblock %}
{% block footer%}
<!--<h3><li><a href='{% url 'rango:add_category' %}'>Top</a></li></h3>-->
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
{{ category.name}}
{% endblock %}

{% block body_block %}
{% if category %}
<h2><atrong>{{ category.name }}</strong></h2>
<form id="add_pages" method='post' action='/rango/{{category.slug}}/add_page/'>
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
<ul>
	<strong>{{ field.errors }}</strong>
	<p>{{ field.help_text }}</p>
	{{ field }}
</ul>
{% endfor %}
<input type='submit' name='submit' value='Submit' class="bg-info">
</form>
{% endif %}
{% endblock %}
{% block footer %}
<ul>
<h3><li class="list-unstyled"><a href='{% url 'rango:add_page' category.slug %}'>Top</a></li>
<li class="list-unstyled"><a href='{% url 'rango:show_category' category.slug %}'>Back</a></li>
</h3>
</ul>
{% endblock%}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
	<head lang="en">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			Rango :::
			{% block title_block %}
				How to Tango with Django!
			{% endblock %}
		</title>
   <!-- Latest compiled and minified CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
	</head>
	<body>
		<nav class="navbar-expand-sm bg-dark navbar-dark ">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcollapse"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarcollapse">
			<ul class="navbar-nav">
				<a class="navbar-brand" href="{% url "rango:index" %}">Rango</a>
				<li class="nav-item">
					<a class="nav-link" href="{% url "rango:index" %}">Home</a>
				</li>	
				<li class="nav-item">
					<a class="nav-link" href="{% url "rango:about" %}">About</a>
				</li>
				<form class="form-inline" action="">
					<input type="text" class="form-control mr-sm-2" placeholder="Search Rango">
					<button type="submit" class="btn btn-success">Search</button>
				</form>
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url "rango:logout" %}">Logout</a>
				</li>
				<span class="navbar-text">You're logged in as {{user.username}} </span>

				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url "rango:register" %}">Register Here</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url "rango:login" %}">Login</a>
				</li>
				<span class="navbar-text"> Welcome, Login to rango</span>
				{% endif %}
			</ul>
		</div>
		</nav>

		<div class="container-fluid jumbotron">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar bg-light">
					{% block sidebar_block %}
					<h4 class="text-center">All categories</h4>
						{% get_category_list %}
					{% endblock %}
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					{% block body_block %}
					{% endblock %}
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					{% block footer%}
					{% endblock %}
					<hr/>
					<p><strong><p>copyright 2018</p></strong></p>
					<hr/>
				</div>
			</div>
		</div>

    <!-- JQuery library-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!--Popper JS-->
    <script src="https://cdnjs.cloudfare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <!--Latest compiled javascript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html'%}

{% block title_block %}
{{ category.name }}
{% endblock %}

{% block body_block%}
	{% if category %}
		{% if error_message %}<strong>{{ error_message }}</strong>{% endif %}
		<h2><form method='post' action='{% url 'rango:likeCategory' category.slug %}'>
		{% csrf_token %}
		<input type="checkbox"  name='category' id='category{{category.slug}}' value='{{ category.slug }}' />
		<label class="form-check-label" for='category{{ category.slug }}'>{{ category.name }}  </label>
		<input type='submit' value = 'like' class="bg-secondary btn btn-sm"/>
		</form>	</h2>
		<strong>{{category.likes}} like{{category.likes|pluralize}}</strong>	<br/>	
		{% if pages %}
		<h3>Pages</h3>
		<ul>
			{% for page in pages %}
				<li><a href='{{page.url}}'>{{ page.title}}</a></li><br/>
			{% endfor %}
		</ul>
		{% else %}
			<strong>No pages currently in {{category.name}}</strong><br/>
		{% endif %}
	{% else %}
		The specified category does not exist!
	{% endif %}

	<nav class="navbar navbar-expand-sm bg-light navbar-light fixed-bottom">
	<ul class="navbar-nav">
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:restricted' %}'>Restricted</a></li>
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:show_category' category.slug %}'>Top</a></li>
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:add_page' category.slug %}'> Add a new Page</a></li>
	</ul>
</nav>
{% endblock %}

templates/rango/cats.html
<ul>
	{% if cats %}
		{% for cat in cats %}
			<li>
				<i><a href='{% url 'rango:show_category' cat.slug%}'>{{cat.slug}}</a></i>
				<strong>{{cat.likes}} like{{cat.likes|pluralize}}</strong>
			</li>
		{% endfor %}
	{% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html'%}
{% load staticfiles %}


{% block body_block %}
{% if user.is_authenticated %}
<div class="display-4">
	<p class="text-center">Welcome, {{user.username.title}} </p>
</div>
{% else %}
<div class="display-4">
	<p class="text-center">Welcome to Rango!</p>
</div>
{% endif %}
	{% if categories %}
		<h2 class="text-center"> Top 5 Most Liked Categories</h2>
		<div class="container-fluid">
		<ul class="text-center">
			{% for category in categories %}
			<li class="list-unstyled">
				<a href='{% url 'rango:show_category' category.slug %}'>{{ category.name }} </a>
				<strong>{{category.likes}} like{{category.likes|pluralize}}</strong>
			</li>
			{% endfor %}
		</ul>
		</div>
		{% else %}
			<strong> There are no categories present</strong>
		{% endif %}
		{% if pages %}
		<h2 class="text-center">Most Viewed Pages</h2>
		<ul class="text-center">
			{% for page in pages %}
			<li class="list-unstyled"><a href='{{page.url}}'>{{ page.title }}</a></li>
			{% endfor %}
			</ul>
		{% endif %}
		<img src="{% static "images/rango.jpg"%}" 
		 class="mx-auto d-block rounded img-fluid "style="width:800px;" alt ='Picture of the Simpsons'/>
		 <br/>
	<nav class="navbar navbar-expand-sm bg-light navbar-light">
	<ul class="navbar-nav">
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:restricted' %}'>Restricted</a></li>
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:index' %}'>Top</a></li>
		<li class="nav-item"><a class="nav-link" href='{% url 'rango:add_category'%}'> Add a new Category</a></li>
	</ul>
</nav>
{% endblock %}
{%block footer %}

{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
 Login
{% endblock %}
{% block sidebar_block %}
<img src="{% static "images/rango.jpg" %}" class="rounded img-fluid " style="width:1200px; height: 300px">
{% endblock %}
{% block body_block %}
<h2 class="text-info"> Login to rango </h2><hr/>
<form id='login_form' method='post' action='{% url 'rango:login' %}'>
	{% csrf_token %}
	<div class="form-group">
	<label for='username'>Username</label>
	<input type='text' name='username' value='' size='50' class="form-control" id="username" placeholder="Username" />
	</div>
	<div class="form-group">
	<label for='password'>Password</label>
	<input type='password' name='password' value='' size='50' class="form-control" id="password" placeholder="Password"/>
	</div>
	<label class="form-check-label">
	<input class="form-check-input" type="checkbox">Remember me
	</label><br/>
	<button type='submit' value='submit' class="btn btn-primary">Submit</button>
</form>
{% if error_message %}
	<h3><strong>{{ error_message }}<strong></h3>
	<h3>Click <a href='{% url 'rango:register' %}'>here</a> to register</h3>
{% endif %}
{% endblock %}
{% block footer %}
<h3><a href='{% url 'rango:index' %}'>Back</a></h3>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Register
{% endblock %}
{% block sidebar_block %}
<img src="{% static "images/rango.jpg" %}" class="rounded img-fluid " style="width:1200px; height: 350px">
{% endblock %}

{% block side_bar %}
{% endblock %}
{% block body_block %}
	{% if registered %}
		<h3><strong>Thanks for registering!</strong></h3>
		<h3><a href='{% url 'rango:login' %}'>Login</a></h3>
	{% else %}
		<h2 class="text-info"><strong>Register here!</strong></h2>
		<form id="user_form" method ="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
		{% csrf_token %}
		<!-- Display each form-->
		{{ user_form.as_p}}
		{{ profile_form.as_p }}
		<!-- Provide a button to click to submit the form -->
		<button type="submit" name="submit" value="Register" class="btn btn-primary">Register</button>
		</form>
	{% endif %}
{% endblock %}
{% block footer %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% block title_block %}
{% endblock %}
{% block body_block %}
{{text}}
{% endblock %}
{% block footer %}
<h3><li><a href='{% url 'rango:index' %}'>Index</a></li></h3>
{% endblock %}